### ISSUE TITLE
Research and Add Useful Linters Mentioned In Denis Isaev's GopherCon 2019 Video

### ISSUE THREAD

**Issue by TekWizely** [TekWizely/pre-commit-golang#1]
Review this video by the creator of golangci-lint and presented at GopherCon 2019:

https://www.youtube.com/watch?v=1U-Gzz4TYP0&list=PL2ntRZ1ySWBdDyspRTNBIKES1Y-P__59_&index=19

It mentions a couple dozen linters - several of which should likely be considered for addition to this project.

**Comment by TekWizely** [comment]
https://superhighway.dev/staticcheck-in-action

**Comment by davidpfarrell** [comment]
https://github.com/securego/gosec
