### ISSUE TITLE
Provide flag for autoformatting

### ISSUE THREAD

**Issue by blaggacao** [TekWizely/pre-commit-golang#2]
I (mis)use pre-commit for automating manually one-off commands too:
https://github.com/xoe-labs/coredns-ldap/blob/0865a9015eae3b325669732237cdbe610a4f14c0/justfile#L3-L5

This way I benefit of using a single environment and code path for both, true pre-commits and one-offs.

However, for one-offs, I'd prefer they modify the code base, if theya re auto-formatters.

Therefore, add a flag to the scripts which allows to switch from check to format mode.

**Comment by TekWizely** [comment]
Added a new section in the README to explain how to use `alias` and `name` to manage hook variants:
* https://github.com/TekWizely/pre-commit-golang#aliases--names

Thanks for creating this issue - It kept nagging at me until I finally figured out a nice way to add it to the docs.

Closing

---

ref: #16
