### ISSUE TITLE
false typecheck failures only occuring in pre-commt lint check

### ISSUE THREAD

**Issue by plastikfan** [TekWizely/pre-commit-golang#31]
I'm attempting to use this pre-commit hook in a number of my projects, but am consistently facing problems with false typecheck errors. When I run golangci-lint in the following cases:

- manually on the command line with: ___golangci-lint run___
- within visual studio via golang plugin
- in github actions ci

these typecheck failures do not occur. They only occur as part of the pre-commit execution. They are usually to do with an identifier not existing but they clearly do otherwise these other ways of running the lint would fail, and the test wouldn't pass and the executbles/library would not be runnable and they are.

So what is the issue here? I have also learned that typecheck is not a real linter, so it can't be disabled, so that's not a workaround. To be honest, I can't see the point of typecheck as it doesn't catch issues that wouldn't be caught by the compiler, its just proving to be a big headache.

Examples of the type of errors I'm seeing can be found here:
- [fix typecheck pre-commit lint failure in new-filter](https://github.com/snivilised/extendio/issues/218)
- [fix bogus typecheck pre-commit lint problem in param-set/param-set-auto](https://github.com/snivilised/arcadia/issues/153)
- [fix the lint setup](https://github.com/snivilised/cobrass/issues/135)

If there is a work-around for this problem, please can you let me know.

**Comment by plastikfan** [comment]
If anyone else is seeing these issues, just use golangci/golangci-lint instead:

```
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
```

**Comment by TekWizely** [comment]
@plastikfan Apologies for not replying sooner ...

Its strange that you could run golangci-lint directly from the command line and get different results than from my git hook.

One thing to know is that I offer 5 different versions fo the hook:
* https://github.com/TekWizely/pre-commit-golang#golangci-lint

And which one you use could affect the results.

If you're still able, can you confirm which version you used?

I would think that the `-repo-mod` version would be the most similar to running it directly from the command line.

I'm glad you worked it out and I appreciate your initial interest in my project.

Sincerely,

-TW

**Comment by plastikfan** [comment]
Hey @TekWizely, thanks for your response. I only just noticed your reply just now. I've moved on from this issue since I found a work-around, but that link you posted looks to be useful and I'll take a look and will be interested to learn more about what this project offers. Cheers for now.

**Comment by CameronHudson8** [comment]
I noticed that `GO111MODULE=off` is set [here](https://github.com/TekWizely/pre-commit-golang/blob/a701af726d456597f5b0c3b55af615451489ceeb/golangci-lint-repo-pkg.sh#L6), and I was able to reproduce the `typecheck` errors by running `GO111MODULE=off golangci-lint run`. Without the variable `GO111MODULE=off`, `golangci-lint run` is successful. ([@plastikfan's suggestion to use golangci-lint directly](https://github.com/TekWizely/pre-commit-golang/issues/31#issuecomment-1515944368) also works.)

**Comment by TekWizely** [comment]
_@CameronHudson8 wrote_
> I noticed that `GO111MODULE=off` is set [here](https://github.com/TekWizely/pre-commit-golang/blob/a701af726d456597f5b0c3b55af615451489ceeb/golangci-lint-repo-pkg.sh#L6)

Greetings!

The `-pkg` hooks exist to support GOPATH development (ie. `GO111MODULE=off`).

It sounds like golangci no-longer fully supports this mode - Which would be no surprise since since Go has been ignoring the `GO111MODULE` variable for awhile now.

I keep the hooks around for people who may be locked into some old version and still find a use for them.

For anyone reading this post - Please use `-mod` version of the hooks unless you explicitly need GOPATH based support.

Thanks for taking the time to comment!
