### ISSUE TITLE
Add `go mod tidy`

### ISSUE THREAD

**Issue by lthibault** [TekWizely/pre-commit-golang#6]
Please consider adding hooks to execute `go mod tidy`

**Comment by TekWizely** [comment]
Greetings!

I'm working on it now :)  Feel free to put a watch on the repo and get notified when the next release goes out (hopefully soon)

Thank you for your interest and taking the time to make an issue !

-TW

**Comment by TekWizely** [comment]
Added in [v1.0.0-beta.2](https://github.com/TekWizely/pre-commit-golang/releases/tag/v1.0.0-beta.2)

Please give it a try and feel free to pen a new issue if you have any problems.
